requirements.txt: use zc.buildout 3.3.
This works with all supported Python versions.
With previous 3.0.1 I get an error on `tox -e plone60-py311`:

```
Requires-Python support missing and could not be patched into zc.buildout.

Traceback (most recent call last):
  File "/Users/maurits/zest/irceline6/src/collective.exportimport/.tox/plone60-py311/lib/python3.11/site-packages/zc/buildout/patches.py", line 66, in patch_PackageIndex
    from pip._vendor import six
ImportError: cannot import name 'six' from 'pip._vendor' (/Users/maurits/zest/irceline6/src/collective.exportimport/.tox/plone60-py311/lib/python3.11/site-packages/pip/_vendor/__init__.py)
```

`zc.buildout` swallows and accepts the error, but as the error says: Requires-Python support is then missing, and we would like to have it.