Fix CI again, for Plone 6.0.
Use more recent zc.buildout and setuptools versions on Python 3.9+.

Sample [failure](https://github.com/collective/collective.exportimport/actions/runs/14313320340/job/40167791650#step:8:1178):

```
While:
  Installing test.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/runner/work/collective.exportimport/collective.exportimport/.tox/plone60-py311/lib/python3.11/site-packages/zc/buildout/buildout.py", line 2300, in main
    getattr(buildout, command)(args)
  File "/home/runner/work/collective.exportimport/collective.exportimport/.tox/plone60-py311/lib/python3.11/site-packages/zc/buildout/buildout.py", line 856, in install
    installed_files = self[part]._call(recipe.install)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/collective.exportimport/collective.exportimport/.tox/plone60-py311/lib/python3.11/site-packages/zc/buildout/buildout.py", line 1659, in _call
    return f()
           ^^^
  File "/home/runner/eggs/zc.recipe.testrunner-3.1-py3.11.egg/zc/recipe/testrunner/__init__.py", line 48, in install
    test_paths = [ws.find(pkg_resources.Requirement.parse(spec)).location
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/eggs/zc.recipe.testrunner-3.1-py3.11.egg/zc/recipe/testrunner/__init__.py", line 48, in <listcomp>
    test_paths = [ws.find(pkg_resources.Requirement.parse(spec)).location
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'location'
```

If the tests still fail after this, we may need one or both of these fixes:

* https://github.com/zopefoundation/zc.recipe.testrunner/pull/21
* https://github.com/buildout/buildout/pull/698