Use latest plone.restapi 9.13.2 on Python 3.8.
This should fix a distribution not found in plone.restapi itself.
But locally it goes wrong with:

```
AttributeError: _DistInfoDistribution__dep_map
```

This really seems to come from this line:

```
  File "/Users/maurits/shared-eggs/cp38/Products.CMFPlone-5.2.15-py3.8.egg/Products/CMFPlone/__init__.py", line 8, in <module>
    __version__ = pkg_resources.require("Products.CMFPlone")[0].version
```

It's a `pkg_resources` mess all the way down...